### ISSUE TITLE
Translate sound into parameters

### ISSUE THREAD

**Issue by SysAdminSfC** [ScienceForChange/soundCollect#12]
add MatLab package "signal processing toolbox" throu CLI into MatLab docker image

**Comment by SysAdminSfC** [comment]
can you put start and end date on this issue pls?

**Comment by CarlosMillanSfC** [comment]
No, by now i cant with this information, i thought there will be some ICR notes or something, and i ask, the package is this one? 
https://www.mathworks.com/products/signal.html

@OtariOboladzeSfC

**Comment by CarlosMillanSfC** [comment]
https://www.mathworks.com/products/signal.html this cost money, i dont think is a good idea to test with the "free" version, i dont understand the porpuse.

**Comment by SysAdminSfC** [comment]
dockerhub image is here: https://hub.docker.com/r/mathworks/matlab
you can run it as: docker run -it --rm --shm-size=512M mathworks/matlab:r2023b
test email: sysadmin@scienceforchange.eu
pswd: sysadmin@scienceforchange.euA1

can you put .m files on shared volume and test input/output on them? @CarlosMillanSfC

**Comment by CarlosMillanSfC** [comment]
@SysAdminSfC @OtariOboladzeSfC 
Aparte de los archivos del correo Fwd: Codigo SPLmeter matlab
y el vídeo de la reunión ICR/SFC (2024-02-19 17:05 GMT+1)

Hay algún otro material? anotaciones, documentos, decisiones sobre la implementación del código de ICR en sound? lo necesitaría para poder implementarlo cuanto antes, que veo que va a ser muy complicado esto y cualquier cosa me ayudaría. Gracias!

**Comment by CarlosMillanSfC** [comment]
Info útil:
https://github.com/mathworks-ref-arch/matlab-dockerfile
https://es.mathworks.com/help/cloudcenter/containers.html

**Comment by CarlosMillanSfC** [comment]
Please enter your MathWorks Account email address and press Enter:
sysadmin@scienceforchange.eu
Please enter your MathWorks Account password and press Enter:

Starting MATLAB with license: 12029295 - Prueba de R2023b: 21 Mzo. 2024
License checkout failed.
License Manager Error 4410
The requested entitlement could not be found. (Status code: EntitlementNotFound)

Troubleshoot this issue by visiting:
https://www.mathworks.com/support/lme/R2022b/4410

Diagnostic Information:
Feature: MATLAB
License path:
Licensing error: 4410,0.

**Comment by CarlosMillanSfC** [comment]
sobre cómo leer los ficheros .WAV es una movida porque los ficheros de sonidos van a estar almacenados en S3, cómo los va a leer el docker de matlab es una muy buena pregunta. Poddía a lo sumo almacenarlo de forma temporal en el docker de api y que de ahí lo comparta con un volumen con el docker de matlab, lo analice y una vez hecho lo suba a S3 y lo borre del servidor...

**Comment by OtariOboladzeSfC** [comment]
necesitamos s3 para audios temporales? no guardamos los audios al final, desde gene nos piden guardar solo parametros, no los audios

**Comment by CarlosMillanSfC** [comment]
@OtariOboladzeSfC desconocía que no se pudieran guardar los audios al final pero igualmente para enviarselos a ICR tienen que estar en algún sitio, no? Se puede borrar después el audio pero entendí que para que el código de ICR funcione tiene que acceder al fichero .WAV y en el servidor no hay nada montado para que se guarde ahí nada, por eso digo s3

Si hay que configurar el servidor para que guarde temporalmente el audio ahí se hace pero me va a tomar tiempo.
