### ISSUE TITLE
Restrict users under 14

### ISSUE THREAD

**Issue by OtariOboladzeSfC** [ScienceForChange/soundCollect#16]
can you add age restriction for users under 14 pls? we need it for declaration of Google Play terms @CarlosMillanSfC

**Comment by OtariOboladzeSfC** [comment]
does this look good? I think we need to change it to (return: "[error code : error message] ") for JSON to be returned
// restrict users under 14 years to register

**Comment by CarlosMillanSfC** [comment]
There was already a validation taking care that the users are not under 15.
https://github.com/ScienceForChange/soundCollect/blob/899bf8b5e13e1e67034c742d9c37479d3ba2c1f1/api/app/Rules/TeenAgeCare.php#L8

I can change it to 14 and all good.
